/**
 * Writing Agent (通常のA2Aエージェント)
 * MCPツールは使用せず、他のエージェントと協調して動作
 */

import { A2AAgent } from '../core/a2a-agent';
import { Task, TaskState } from '../types/a2a-protocol';

export class WritingAgent extends A2AAgent {
  constructor(port: number) {
    super({
      name: 'writing-agent',
      description: 'Agent specialized in content writing and editing',
      port,
      organization: 'AEGIS A2A Demo',
      organizationUrl: 'https://github.com/aegis-project',
      capabilities: {
        supportedTaskTypes: ['write', 'edit', 'proofread', 'translate']
      },
      metadata: {
        version: '1.0.0',
        language: 'en',
        specialties: ['technical-writing', 'documentation', 'articles']
      }
    });
  }

  protected async processTask(task: Task): Promise<void> {
    this.logger.info(`Processing writing task: ${task.id}`);
    
    try {
      await this.updateTaskState(task.id, TaskState.WORKING, {
        progress: {
          current: 0,
          total: 100,
          message: 'Starting writing task'
        }
      });

      const result = await this.performWriting(task.prompt, task);

      await this.updateTaskState(task.id, TaskState.COMPLETED, {
        result
      });
    } catch (error) {
      await this.updateTaskState(task.id, TaskState.FAILED, {
        error: error instanceof Error ? error.message : 'Unknown error'
      });
    }
  }

  private async performWriting(prompt: string, task: Task): Promise<any> {
    // プログレス更新
    await this.updateTaskState(task.id, TaskState.WORKING, {
      progress: {
        current: 50,
        total: 100,
        message: 'Generating content'
      }
    });

    // シンプルなコンテンツ生成（MCPツールなし）
    const content = this.generateContent(prompt);

    return {
      content,
      type: 'article',
      wordCount: content.split(/\s+/).length,
      language: 'en',
      metadata: {
        generatedAt: new Date().toISOString(),
        agent: this.config.name,
        taskContext: {
          taskId: task.id,
          delegationChain: task.metadata?.delegationChain || [],
          priority: task.metadata?.priority || 'normal'
        }
      }
    };
  }

  private generateContent(prompt: string): string {
    // 実際のLLMの代わりにシンプルなテンプレート生成
    return `# ${prompt}

This content was generated by the Writing Agent without using MCP tools.

## Overview
The Writing Agent operates as a standard A2A agent, collaborating with other agents through the A2A protocol.

## Key Features
- Pure A2A agent without MCP integration
- Collaborates with MCP-enabled agents when needed
- Focuses on content creation and editing

## Collaboration Example
When advanced research is needed, this agent can delegate tasks to the Research Agent, which has access to MCP tools through AEGIS policy control.

## Conclusion
This demonstrates the flexibility of the A2A architecture, where not all agents need direct tool access.`;
  }

  getCapabilities(): any {
    return {
      name: this.config.name,
      description: this.config.description,
      supportedTasks: ['write', 'edit', 'proofread', 'translate'],
      mcpEnabled: false,
      metadata: this.config.metadata
    };
  }
}